In [ ]:
'''from google.colab import drive
drive.mount('/content/drive')
!pip install deepchem rdkit matplotlib networkx
'''
import deepchem as dc
from rdkit import Chem
from rdkit.Chem import Draw
import matplotlib.pyplot as plt
import networkx as nx
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from deepchem.feat import MolGraphConvFeaturizer
from deepchem.feat import CircularFingerprint
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from deepchem.feat import ConvMolFeaturizer
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors
import deepchem as dc
from methods_fingerprints import *

#from drive.MyDrive.code.methods import *
#from drive.MyDrive.code.methods_fingerprints import *

Mounted at /content/drive
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 15.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.1/33.1 MB 35.7 MB/s eta 0:00:00


Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead


In [ ]:
smiles_tr,smiles_test, logSweeter_tr, logSweeter_test, families_tr, families_test = load_data_remove("../data/SweetnersDB.xlsx")
X_tr,X_test,scaler_X = prepare_fingerprint(smiles_tr,smiles_test)
y_tr,y_test,scaler_y = prepare_targets(logSweeter_tr,logSweeter_test)

Index(['Name', 'logSw', 'Chemical family', 'Dataset', 'Smiles'], dtype='object')


[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerator
[15:06:42] DEPRECATION WARNING: please use MorganGenerat

In [ ]:
onehot_tr,onehot_test = prepare_famille_chimique(families_tr, families_test)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
representation_tr = np.hstack((X_tr, onehot_tr))
representation_test = np.hstack((X_test,onehot_test))

In [ ]:
smiles_tr.shape

(250,)

# scoring reg log

In [ ]:
accuracy_log,conf_matrix_log,class_report_log,y_pred_log,target_test_log = scoring(y_tr,y_test,representation_tr,representation_test,0,'LogReg')

Accuracy: 0.7903225806451613
Confusion Matrix:
[[16  5]
 [ 8 33]]
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.76      0.71        21
           1       0.87      0.80      0.84        41

    accuracy                           0.79        62
   macro avg       0.77      0.78      0.77        62
weighted avg       0.80      0.79      0.79        62



# scoring decision tree

In [ ]:
accuracy_tree,conf_matrix_tree,class_report_tree,y_pred_tree,target_test_tree = scoring(y_tr,y_test,representation_tr,representation_test,0,'DecisionTree')

Accuracy: 0.8387096774193549
Confusion Matrix:
[[15  6]
 [ 4 37]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.71      0.75        21
           1       0.86      0.90      0.88        41

    accuracy                           0.84        62
   macro avg       0.82      0.81      0.82        62
weighted avg       0.84      0.84      0.84        62



In [ ]:
accuracy_rf,conf_matrix_rf,class_report_rf,y_pred_rf,target_test_rf = scoring(y_tr,y_test,X_tr,X_test,0,"RandomF")

Accuracy: 0.8709677419354839
Confusion Matrix:
[[15  6]
 [ 2 39]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.71      0.79        21
           1       0.87      0.95      0.91        41

    accuracy                           0.87        62
   macro avg       0.87      0.83      0.85        62
weighted avg       0.87      0.87      0.87        62



# scoring svm

In [ ]:
accuracy_svm,conf_matrix_svm,class_report_svm,y_pred_svm,target_test_svm = scoring(y_tr,y_test,X_tr,X_test,0,"SVM")

Accuracy: 0.8387096774193549
Confusion Matrix:
[[12  9]
 [ 1 40]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.57      0.71        21
           1       0.82      0.98      0.89        41

    accuracy                           0.84        62
   macro avg       0.87      0.77      0.80        62
weighted avg       0.85      0.84      0.83        62

